services:
  postgres:
    environment:
      - POSTGRES_USER=poupaai
      - POSTGRES_PASSWORD=pBsV0y975KFrxq9J
      - POSTGRES_DB=PoupaAiDb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  poupa.ai.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - DATABASE_CONNECTION_STRING=Host=poupa_ai_postgres;Port=5432;Database=PoupaAiDb;Username=poupaai;Password=pBsV0y975KFrxq9J
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro