services:
  postgres:
    image: postgres:13
    container_name: poupa_ai_postgres
    environment:
      - POSTGRES_USER=poupaai
      - POSTGRES_PASSWORD=pBsV0y975KFrxq9J
      - POSTGRES_DB=PoupaAiDb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - poupa_ai_network
  poupa.ai.api:
    image: ${DOCKER_REGISTRY-}poupaaiapi
    build:
      context: .
      dockerfile: src/Poupa.AI.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8081
      - ASPNETCORE_HTTPS_PORTS=8082
      - DATABASE_CONNECTION_STRING=Host=poupa_ai_postgres;Port=5432;Database=PoupaAiDb;Username=poupaai;Password=pBsV0y975KFrxq9J
    ports:
      - "8081"
      - "8082"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - poupa_ai_network

networks:
  poupa_ai_network:

volumes:
  postgres-data:
